// This code was generated by a cloud-generators-net tool 
// (see https://github.com/Kentico/cloud-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System.Collections.Generic;
using Newtonsoft.Json;
using KenticoCloud.ContentManagement.Models.Items;

namespace GithubService.Models.KenticoCloud
{
    public partial class CodeSamples
    {
        [JsonProperty("code_samples")]
        public IEnumerable<ContentItemIdentifier> Samples { get; set; }
    }
}